### PR TITLE
Development for PX4Flow 2.0 hardware

### PR DESCRIPTION
**Pull request by kevinmehall**
* Switch to KLT algorithm (from Simon Laube, Severin Latkovic, Petri Tanskanen)
* Rewritten camera driver (from Simon Laube)
* Improved camera parameters (fixing #41 and other observed issues)
* Implement UAVCAN messages with flow and range data
* LED drivers split for V1 vs V2 hardware (RGB color based on flow quality on V2 hardware)
* Split I2C slave driver into a module, only enabled on V1
* Split Sonar driver into a module, only enabled on V1
* Add driver module for Pulsed Light Lidar-Lite via I2C (from Tom Cauchois)
* Add driver module for Lightware SF10 via I2C, enabled on V2 hardware
* Refactoring and code cleanup

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome, thanks! Let me see what Travis says..

**Comment by LorenzMeier** [comment]
@scott-eddy Here is the KLT flow if you're interested in playing with it.

**Comment by LorenzMeier** [comment]
@kevinmehall @laube Any idea why Travis runs into this compile error?

```
CC:      /home/travis/build/PX4/Flow/src/modules/flow/camera.c
/home/travis/build/PX4/Flow/src/modules/flow/camera.c: In function 'camera_img_stream_get_buffers':
/home/travis/build/PX4/Flow/src/modules/flow/camera.c:145:45: error: array subscript is above array bounds [-Werror=array-bounds]
   ctx->buf_avail[i - count] = ctx->buf_avail[i];
                                             ^
compilation terminated due to -Wfatal-errors.
cc1: some warnings being treated as errors
```

**Comment by kevinmehall** [comment]
I ignored a similar error: https://github.com/kevinmehall/Flow/commit/0c05b0ab3ef4ccf1717cd61394f7e1d0a01968b9, which I thought was in an unreachable version after unrolling and inlining (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59124), but I haven't seen that one using gcc-arm-embedded 4.9.3 20150529. It might be a good idea to add a run-time bounds check to both of these to be sure.

**Comment by laube** [comment]
jep, we have seen this error before but only on GCC > 4.7.4. adding a runtime-check fixed it. I looked countless times over the code and couldn't see why GCC thinks there is an index error.

I would go with the runtime-check. Just add something like
```
for (i = count; i < bc && i < <array-size>; ++i) {
```
I know it is not nice to ignore the warning of GCC like this in case GCC is right and there is a corner case (or possibly a race condition) where the index will overflow.

**Comment by scott-eddy** [comment]
@laube @kevinmehall I'd love to compile this and try it out.  I'm still getting the error when making even though that line contains your suggested runtime check 
(e.g. `for (i = count; i < bc && i < CONFIG_CAMERA_MAX_BUFFER_COUNT; ++i) `)

Any suggestions?

**Comment by laube** [comment]
Try the changes from 0c05b0a. It will silence the warnings.

**Comment by mhkabir** [comment]
@laube @kevinmehall I'm using the latest head, and the build issue is still present :

**Comment by scott-eddy** [comment]
@mhkabir I was able to manually add the changes from 0c05b0a and build the firmware as suggested by laube.

**Comment by mhkabir** [comment]
@scott-eddy Thanks, worked. I was incorrect in assuming that the fix was already applied for my case since it's a commit in the PR.

**Comment by mhkabir** [comment]
OK, so I got this working now. The issue now is that no video is sent to the ground station. I'm experimenting with several lens options, and no live feed makes it impossible to work with. 
Could someone have a look?

**Comment by LorenzMeier** [comment]
@mhkabir You have to set the video param to 0 to enable it. Not sure yet why.

**Comment by LorenzMeier** [comment]
Closing this and re-opening with build fix.

**Pull request closed without merging**
