### PR TITLE
Added sonar status to flow frame and added mode filter disable param

### PR DESCRIPTION
**Pull request by jgoppert**
This is the last bit to add the sonar status to the i2c frame for the flow. We should change to a new minor version number on the flow since this modifies the existing communication protocol.

### CODE REVIEW

**Comment by jgoppert** [comment]
This also includes the mode filter disable parameter.

**Comment by jgoppert** [comment]
I just did a lot of optical flow testing with both the Firmware/Flow flow-sonar-status branches so they should be ready.

**Comment by LorenzMeier** [comment]
Still blocked on https://github.com/PX4/Firmware/pull/1722, as we need to have a strategy how to push this update into the deployed base.

**Comment by bsbandwl** [comment]
Sonar Mode Filter? 
After Bubble Sort, the function will return the median of lastest 3 sonar samples I think, not the mode.
So why not Median Filter?

**Comment by LorenzMeier** [comment]
I think the right fix is to either improve or completely remove the sonar mode filtering. Closing this and not changing the interface.

**Pull request closed without merging**
