### PR TITLE
use FLOAT_AS_BOOL() to avoid warning

### PR DESCRIPTION
**Pull request by ChristophTobler**

### CODE REVIEW

**Comment by TSC21** [comment]
@ChristophTobler what warning were we getting when compiling the code?

**Comment by ChristophTobler** [comment]
```
warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
  if (global_data.param[PARAM_USB_SEND_VIDEO] )//&& global_data.param[PARAM_VIDEO_USB_MODE] == FLOW_VIDEO)
```

**Comment by TSC21** [comment]
Ok. Any other warnings we should take care of?

**Comment by ChristophTobler** [comment]
Nope. I don't get any other warnings

**Pull request merged**
